config/routes.rb
Rails.application.routes.draw do
  #http   location    controller#method  alias
  get '/herbs', to: 'herb#index', as: 'herbs'
  get '/herbs/new', to: 'herb#new', as: 'herb_new'
  get '/herbs/:id', to: 'herb#show', as: 'herb'
  post '/herbs', to: 'herb#create'
  get '/herbs/:id/edit', to: 'herb#edit', as: 'edit_herb'
  patch 'herbs/:id', to: 'herb#update'
  delete '/herbs/:id', to: 'herb#destroy', as: 'delete_herb'
  root 'herb#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/herb.rb
class Herb < ApplicationRecord
  validates :name, :watered, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/herb_controller.rb
class HerbController < ApplicationController
  def index
    @herbs = Herb.all
  end

  def show
    @herb = Herb.find(params[:id])
    #return show.html.erb
  end

  def new
    @herb = Herb.new
  end

  def create
    @herb = Herb.create(herb_params)
    if @herb.valid?
      redirect_to herbs_path
    end
  end

  def edit
    @herb = Herb.find(params[:id])
  end

  def update
    @herb = Herb.find(params[:id])
    @herb.update(herb_params)
    if @herb.valid?
      redirect_to herb_path(@herb)
    end
  end

  def destroy
    @herb = Herb.find(params[:id])
    @herb.destroy
    redirect_to herbs_path
  end

  private
  def herb_params
    params.require(:herb).permit(:name, :watered)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/herb/_form.html.erb
<%= form_with model: @herb do |form| %>
  <%= form.label :name, 'Enter Herb Name' %>
  <br />
  <%= form.text_field :name %>
  <br />
  <br />
  <%= form.radio_button :watered, "Yes" %>
  <%= form.label :watered, "The herb has been watered" %>
  <br />
  <%= form.radio_button :watered, "No" %>
  <%= form.label :watered, "The herb has NOT been watered" %>
  <br />
  <br />
  <%= form.submit %>
<% end %>

app/views/herb/edit.html.erb
<h3>Edit Your Herb</h3>

<%= render partial: 'form', locals: {herb: @herb} %>

<p><%= link_to 'Home', herbs_path %></p>

app/views/herb/index.html.erb
<h1>Herb Garden App</h1>
<ul>
  <% @herbs.each do |herb| %>
    <li><%= link_to herb.name, herb_path(herb) %></li>
  <% end %>
</ul>

<p><%= link_to 'Create New Herb', herb_new_path %></p>

app/views/herb/new.html.erb
<h3>Add a New Herb to the Garden</h3>

<%= render partial: 'form', locals: {herb: @herb} %>

<p><%= link_to 'Home', herbs_path %></p>

app/views/herb/show.html.erb
<h3>Herb Details</h3>

<p>Name of the herb: <%= @herb.name %></p>
<p>Has the herb been watered: <%= @herb.watered %></p>

<p><%= link_to 'Edit Herb', edit_herb_path(@herb) %></p>
<p><%= link_to 'Delete Herb', delete_herb_path(@herb), data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete #{@herb.name}?" } %></p>
<p><%= link_to 'Home', herbs_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFullStack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>